import Head from "next/head"
import { useRouter } from "next/router"

const Category = () => {

  const router = useRouter()

  const {image} = router.query
  

  return (
   
    <div className="min-h-screen bg-[#030303] text-gray-50">
       <Head>
        <title>Discover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-[4rem] px-[1rem] md:px-[6rem]">
      <p className="font-medium">TSIB</p>
      <div className="w-full h-[30rem] bg-cover" style={{backgroundImage: `url(${image})`}} ></div>
      </div>
    </div>
  )
}

export default Category